### ISSUE TITLE
Test Issue - Create Project Board in Github

### ISSUE THREAD

**Issue by dkapulkin** [ni/data-record-ad#6]
As an admin for this mostly-open source project, I need to be able to host my backlog, assign tasks, and show priority in Github rather than an internal tool. Anyone with a Github account and access to the repo should be able to see this.

**Comment by JLMommy** [comment]
I can see this.

**Comment by dkapulkin** [comment]
this is the public repo - so outside the org folks can see this. That's good. We'll do the actual project board tracking in the private repo. I was mostly doing this one to confirm I didn't have project-level permissions on NI's repo :) I don't.

**Comment by dkapulkin** [comment]
I now have privileges to create Project Boards. @JLMommy , could you please let me know what cards you can see there?
